FROM node:20-bullseye-slim

WORKDIR /app
COPY package.json package-lock.json* ./
COPY apps/intranet/package.json apps/intranet/
COPY packages/config/package.json packages/config/
COPY packages/db/package.json packages/db/
COPY packages/ui/package.json packages/ui/
RUN npm install --workspaces --include-workspace-root

COPY . .
RUN chmod +x /app/docker/entrypoint.sh
RUN npm --workspace packages/db run generate
WORKDIR /app/apps/intranet
RUN npm run build

EXPOSE 3001
ENTRYPOINT ["/app/docker/entrypoint.sh"]
CMD ["node", ".next/standalone/server.js"]
